
import __ASTRO_IMAGE_IMPORT_2ljtRH from "/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_ZCcPMS from "/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_1trWks from "/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_Z1u4nl8 from "/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_BApMd from "/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z2lUTSn from "/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_1oANRb from "/src/images/speakers/anna-muller.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fanna-muller.md";
import __ASTRO_IMAGE_IMPORT_ZLBtn0 from "/src/images/speakers/emil-steiner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Femil-steiner.md";
import __ASTRO_IMAGE_IMPORT_1STj9U from "/src/images/speakers/javier-garcia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fjavier-garcia.md";
import __ASTRO_IMAGE_IMPORT_22t9lv from "/src/images/speakers/martina-rossi.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fmartina-rossi.md";
import __ASTRO_IMAGE_IMPORT_8TaGD from "/src/images/speakers/miguel-santos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fmiguel-santos.md";
import __ASTRO_IMAGE_IMPORT_Z2t23XD from "/src/images/speakers/sofia-hagblom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fsofia-hagblom.md";
import __ASTRO_IMAGE_IMPORT_Z62ECJ from "/src/images/sponsors/google.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fgoogle.md";
import __ASTRO_IMAGE_IMPORT_2jqcce from "/src/images/sponsors/medium.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fmedium.md";
import __ASTRO_IMAGE_IMPORT_1DdC48 from "/src/images/sponsors/polar-sh.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fpolar-sh.md";
import __ASTRO_IMAGE_IMPORT_19W0CJ from "/src/images/sponsors/swissted.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fswissted.md";
export default new Map([["/src/images/blog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_2ljtRH], ["/src/images/blog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_ZCcPMS], ["/src/images/blog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_1trWks], ["/src/images/blog/4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_Z1u4nl8], ["/src/images/blog/5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_BApMd], ["/src/images/blog/6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z2lUTSn], ["/src/images/speakers/anna-muller.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fanna-muller.md", __ASTRO_IMAGE_IMPORT_1oANRb], ["/src/images/speakers/emil-steiner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Femil-steiner.md", __ASTRO_IMAGE_IMPORT_ZLBtn0], ["/src/images/speakers/javier-garcia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fjavier-garcia.md", __ASTRO_IMAGE_IMPORT_1STj9U], ["/src/images/speakers/martina-rossi.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fmartina-rossi.md", __ASTRO_IMAGE_IMPORT_22t9lv], ["/src/images/speakers/miguel-santos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fmiguel-santos.md", __ASTRO_IMAGE_IMPORT_8TaGD], ["/src/images/speakers/sofia-hagblom.png?astroContentImageFlag=&importer=src%2Fcontent%2Fspeakers%2Fsofia-hagblom.md", __ASTRO_IMAGE_IMPORT_Z2t23XD], ["/src/images/sponsors/google.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fgoogle.md", __ASTRO_IMAGE_IMPORT_Z62ECJ], ["/src/images/sponsors/medium.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fmedium.md", __ASTRO_IMAGE_IMPORT_2jqcce], ["/src/images/sponsors/polar-sh.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fpolar-sh.md", __ASTRO_IMAGE_IMPORT_1DdC48], ["/src/images/sponsors/swissted.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fsponsors%2Fswissted.md", __ASTRO_IMAGE_IMPORT_19W0CJ]]);
		